### ISSUE TITLE
Write to S3 using server-side encryption

### ISSUE THREAD

**Issue by copester** [blaze/odo#166]
As a developer, I want to copy data to S3 such that the resulting objects are encrypted, so that I can use Odo with sensitive data.

boto's set_contents_from_filename() can take an optional parameter encrypt=True, so there needs to be a way to pass that through the call chain such as append_text_to_s3().

Acceptance criteria:
Save data to S3 in a bucket such that the resulting object is encrypted with AES-256. One way to test this is that a bucket with the following policy, will not allow unencrypted puts:
```
{
   "Version":"2012-10-17",
   "Id":"PutObjPolicy",
   "Statement":[{
         "Sid":"DenyUnEncryptedObjectUploads",
         "Effect":"Deny",
         "Principal":"*",
         "Action":"s3:PutObject",
         "Resource":"arn:aws:s3:::mybucket/*",
         "Condition":{
            "StringNotEquals":{
               "s3:x-amz-server-side-encryption":"AES256"
            }
         }
      }
   ]
}
```

**Comment by cpcloud** [comment]
This looks like a nice idea. I don't think it would be too difficult either. I can get to this in roughly a week or two. I'd also happily review a pull request before then.
