### ISSUE TITLE
odo + Spark + Python 3.4? 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [blaze/odo#263]
When trying to follow the [installation instructions](http://odo.readthedocs.org/en/latest/spark.html),  I run into unsatisfiable specifications:

```
$ conda install pyhive spark -c blaze
Fetching package metadata: ........
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##############| 100%

Hint: the following packages conflict with each other:
  - spark
  - python 3.4*
```

Why? Is the support for Python 3.4 not there yet? 
[Here](https://gist.github.com/amelio-vazquez-reina/644299cba3db7b29e825) is my `pip freeze`.

**Comment by cpcloud** [comment]
We don't currently have a spark package for python 3.x, that's why this is failing.

**Comment by amelio-vazquez-reina** [comment]
Thank you @cpcloud I would like happy to help with that. Is there any way in which I can help? Where can I find more info on why we don't have a package yet?

**Comment by amelio-vazquez-reina** [comment]
@cpcloud Happy new year. Do you know if there has been any progress on brining Spark to Python 3.5  (via `conda` install)?

**Comment by quasiben** [comment]
@amelio-vazquez-reina there are spark conda packages in the anaconda-cluster channel on anaconda.org include Python 3.5: https://anaconda.org/anaconda-cluster/spark/files

Spark 1.6 should be available shortly

```
conda install -c anaconda-cluster spark
```

**Comment by amelio-vazquez-reina** [comment]
Thank you @quasiben. Currently, when I do:
```
$ conda install -c anaconda-cluster spark
```

I get:
```
Fetching package metadata: ........
Solving package specifications: ......
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##########################################################################################################################################| 100%


Hint: the following packages conflict with each other:
  - spark
  - python 3.5*

Use 'conda info spark' etc. to see the dependencies for each package.
```

Is it not available for Python 3.5 ?

**Comment by quasiben** [comment]
What OS are you on ?

**Comment by amelio-vazquez-reina** [comment]
Thanks @quasiben. OS X El Capitan, more details below:

![screen shot 2016-01-05 at 10 01 28 am](https://cloud.githubusercontent.com/assets/1993919/12118235/51966e76-b393-11e5-9696-6a4049e6ea71.png)

**Comment by quasiben** [comment]
Ah -- we only have them for linux at the moment.  I'll resolve this today with latest spark

**Comment by amelio-vazquez-reina** [comment]
Fantastic. Thanks @quasiben !

**Comment by quasiben** [comment]
Python 3.5 for spark 1.6 on OSX is up now. I'll get Linux packages built tomorrow

**Comment by amelio-vazquez-reina** [comment]
Thanks @quasiben That worked great!  Closing now.

**Comment by amelio-vazquez-reina** [comment]
Hi @quasiben I run into an strange warning today, not sure why:

```
$ conda update --all
Fetching package metadata: ......
Warning: No packages found in current osx-64 channels matching: spark, skipping
Solving package specifications: ............................................................................................................................................................................................
Package plan for installation in environment /Users/avazquez/anaconda/envs/py35:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bokeh-0.11.0               |           py35_1         4.2 MB

The following packages will be UPDATED:

    bokeh:   0.10.0-py35_0 --> 0.11.0-py35_1

The following packages will be DOWNGRADED:

    openssl: 1.0.2d-0      --> 1.0.1k-1
    python:  3.5.1-0       --> 3.5.0-0
```

I do have spark installed via `conda`, and it works quite well, I have to say. Any thoughts on why I am getting the warning?

**Comment by quasiben** [comment]
Hmm.  I'm not sure.  Possibly conda update looks at the channels defined in `.condarc`.  Can you trying `conda update spark -c anaconda-cluster`
