### ISSUE TITLE
can not use an existing DataFrame as target in odo(source, target)

### ISSUE THREAD

**Issue by ywang007** [blaze/odo#283]
It seems an existing DataFrame can't be used as target, even when its datashape matches source, not sure if this is intentional, or a bug?

for example:
```
csv = resource('test.csv')
df = odo(csv, pd.DataFrame) #initialize same as csv
odo(df, csv) #fine, simply append df content to csv
odo(csv, df) #throws NotImplementedError 
```
among csv, list, db (sqlite), they all can convert (append) between each other without issue, but none of them can be converted (append) to existing DataFrame. 
Specifically:
self appending -- odo(x,x) works fine for csv, list, sqlite etc, but
odo(df, df) does not work.

**Comment by cpcloud** [comment]
I don't think `DataFrame`s have a way to append in-place. @jreback Is there a way to append to a `DataFrame` that mutate the frame?

**Comment by cpcloud** [comment]
@ywang007 All of the other data sources you listed are mutated when they are append to. You'll see the same error with `numpy` arrays as you will with `DataFrame`s

**Comment by jreback** [comment]
right this in an-inplace operation. So I would agree with @cpcloud that an appendable in-place is not allowed (though useful). 

so mabye raise a better error ,e g. ``ValueError("cannot append in-place")`` or ``target must be mutable``

**Comment by cpcloud** [comment]
yes, it doesn't really make a whole lot of sense to append in place to things that have contiguous blocks of memory, as you'll constantly be reallocating memory. A better solution is to allocate once and fill in, which is essentially what `pandas.concat` does

**Comment by cpcloud** [comment]
(this isn't strictly true, e.g., `list` does this very efficiently, but numpy arrays weren't designed up front with this use case in mind)

**Comment by cpcloud** [comment]
agree on the error message

**Comment by ywang007** [comment]
Yep a more precise error message sure helps.

And in the doc, I’ll add a line about appending behavior for existing data source.
