### ISSUE TITLE
Pathological runtimes with specific CSV files

### ISSUE THREAD

**Issue by kwmsmith** [blaze/odo#340]
As reported by @jbednar 

The file `data.csv` has 3 named columns with trailing commas and a trailing space.  `pandas.read_csv()` can handle this fine, while `odo` completes, but takes several hundred times longer to complete.

```
$ head data.csv
a,b,c, 
-1.3700737E7, 6275190.0, w, 
-1.3700711E7, 6275195.0, w, 
-1.3702081E7, 6274898.5, w, 
-1.3701948E7, 6274931.0, w, 
-1.3701793E7, 6275088.5, w, 
-1.3701224E7, 6274994.5, w, 
-1.370176E7, 6274780.0, w, 
-1.370215E7, 6274539.5, w, 
-1.3702123E7, 6274279.0, w, 

$ wc -l data.csv
  306675005 data.csv
```

`odo`ing the first 10**6 lines of this file into a `DataFrame` takes approximately 30s, meaning the entire 300M line file will take upwards of 2.5 hours to load.

```python
In [4]: %time odo('data_1E6.csv', DataFrame)
CPU times: user 29.7 s, sys: 74.6 ms, total: 29.8 s
Wall time: 29.8 s
Out[4]:
        a            b             c Unnamed: 3
0        -13700737    6275190.0    w 2015-10-23
1        -13700711    6275195.0    w 2015-10-23
2        -13702081    6274898.5    w 2015-10-23
3        -13701948    6274931.0    w 2015-10-23
4        -13701793    6275088.5    w 2015-10-23
5        -13701224    6274994.5    w 2015-10-23
6        -13701760    6274780.0    w 2015-10-23
7        -13702150    6274539.5    w 2015-10-23
8        -13702123    6274279.0    w 2015-10-23
9        -13702072    6274537.0    w 2015-10-23
10       -13701917    6274562.5    w 2015-10-23
```

The equivalent `pandas.read_csv()` call takes approximately 3 minutes to load *the entire file*.

The `odo` call has trouble with the trailing commas and trailing spaces.  It extracts an unnamed column, and the key performance killer is that odo [*converts the space in that column into a datetime*](https://github.com/blaze/odo/blob/master/odo/backends/pandas.py#L60-L61).

Fix is forthcoming.

**Comment by jbednar** [comment]
Ouch!  Thanks for figuring that out; it will be a big help!

**Comment by cpcloud** [comment]
@kwmsmith @jbednar I'm unable to reproduce this performance issue.

@jbednar can you show your odo version?

**Comment by cpcloud** [comment]
@kwmsmith I'm also not seeing the date behavior. What version of pandas are you on?

**Comment by kwmsmith** [comment]
```python
In [1]: cat load_census_blaze.py
from __future__ import print_function

import blaze
import pandas

p = blaze.Data('2010Census_1E6.csv') # just the first 10**6 rows.
plocs = p[['meterswest', 'metersnorth']]
people = blaze.into(pandas.DataFrame, plocs).values

In [2]: %run -t load_census_blaze.py

IPython CPU timings (estimated):
  User   :      33.16 s.
  System :       3.18 s.
Wall time:      34.43 s.

In [3]: import odo

In [4]: odo.__version__
Out[4]: '0.3.4+57.g5af9d90'

In [5]: p.dshape
Out[5]:
dshape("""var * {
  meterswest: ?float64,
  metersnorth: ?float64,
  race: ?string,
  'Unnamed: 3': ?datetime
  }""")
```
Note the `Unnamed 3` column with the `?datetime` type.

@cpcloud Are you using the same data?  What do you get?

**Comment by cpcloud** [comment]
Can you do this without blaze, just `odo('path/to.csv', pd.DataFrame)`?

**Comment by kwmsmith** [comment]
Same result.

**Comment by kwmsmith** [comment]
@cpcloud for the record, I've zeroed in on the issue, and have a fix in the works.

**Comment by cpcloud** [comment]
```
╭─pcloud@phillip-cloud  ~/Downloads  ‹py34›
╰─$ wc -l data_1e6.csv
 10000000 data_1e6.csv
╭─pcloud@phillip-cloud  ~/Downloads  ‹py34›
╰─$ ipyhton
zsh: command not found: ipyhton
╭─pcloud@phillip-cloud  ~/Downloads  ‹py34›
╰─$ ipy                                                                                                                     127 ↵

In [1]: from odo import odo

In [2]: %time df = odo('data_1e6.csv', pd.DataFrame)
CPU times: user 5.01 s, sys: 633 ms, total: 5.64 s
Wall time: 5.65 s

In [4]: !head data_1e6.csv
meterswest,metersnorth,race,
-1.3700737E7, 6275190.0, w,
-1.3700711E7, 6275195.0, w,
-1.3702081E7, 6274898.5, w,
-1.3701948E7, 6274931.0, w,
-1.3701793E7, 6275088.5, w,
-1.3701224E7, 6274994.5, w,
-1.370176E7, 6274780.0, w,
-1.370215E7, 6274539.5, w,
-1.3702123E7, 6274279.0, w,

In [5]: import odo

In [6]: odo.__version__
Out[6]: '0.3.4+57.g5af9d90'
```

**Comment by cpcloud** [comment]
@kwmsmith can you show your pandas version?

**Comment by kwmsmith** [comment]
```
In [8]: pandas.__version__
Out[8]: '0.16.2'
```

**Comment by cpcloud** [comment]
interesting ... this doesn't appear in pandas 0.17.0 ... cool put up the PR and ill review

**Comment by cpcloud** [comment]
there's also a tiny blaze bug fix for this as well (not a perf issue but a fundamental failure) which i'll put up

**Comment by kwmsmith** [comment]
@cpcloud Yep, updating to Pandas 0.17 definitely fixes the issue.

It comes down to `pd.to_datetime(' ', errors='ignore')` returning `' '` in 0.17, whereas in 0.16 `pd.to_datetime(' ') == datetime(2015, 10, 23)` during odo's type discovery.  When reading in the whole file, then, Pandas has to do datetime parsing on that last fake column, which is hundreds of times slower, overall.

So I'm not sure what the best route is -- should I continue to work on this fix, or should we just make odo depend on pandas 0.17?  How far back in pandas versions do we support?

**Comment by jreback** [comment]
@cpcloud as an aside, you *might* want to do some caching on discovery when this gets down into that try/accept around datetimes (when you did that bug fix for ``pd.to_datetime('INF')`` that did ``OverflowError: cannot convert float infinity to integer`` butg)

**Comment by cpcloud** [comment]
@kwmsmith we should probably at least support the 2 most recent versions ... if your fix doesn't require significantly more work i'd say put it up and we can iterate on it if need be

**Comment by kwmsmith** [comment]
> @kwmsmith we should probably at least support the 2 most recent versions ... if your fix doesn't require significantly more work i'd say put it up and we can iterate on it if need be

OK, PR forthcoming.

**Comment by kwmsmith** [comment]
#342 closes this issue.
