### ISSUE TITLE
Amazon RDS

### ISSUE THREAD

**Issue by ptdel** [blaze/odo#352]
perhaps this is a bit outside the scope of the project, I was wondering if there were any plans to provide support for amazon RDS.  RDS does not allow for loading of files on the local filesystem and there are restrictions to SUPER privileges. I wasn't sure if this was going to be a limitation with no answer that allowed for leveraging native loaders.

**Comment by rotten** [comment]
You should try the SQL URL option instead of the file based options.  [ seen here in the documentation:  http://odo.pydata.org/en/latest/sql.html ]

**Comment by ptdel** [comment]
that's exactly what I needed looks like I didn't do enough digging O_O
