### ISSUE TITLE
Mongo support on Windows

### ISSUE THREAD

**Issue by kwmsmith** [blaze/odo#402]
All indications are that MongoDB support on Windows has been broken and not used for some time.  If this is mistaken, we would love to hear about your usecase.

Due to support overhead and the incurred development inertia, my preference for dealing with mongo on windows given current development resources is the following:

* Disable mongo on windows, skipping the test suite, etc.
* Document the lack of support on windows appropriately
* Solicit end users who need mongo on windows to make their usecase known.

I propose disabling mongo support on windows for the full 0.4.1 release in odo and the next bugfix release of blaze.

@sandhujasmine I believe you have some familiarity with mongo and blaze: what's your experience here, specifically w.r.t. windows?

**Comment by sandhujasmine** [comment]
I don't have a use case for mongo/blaze on Windows.

**Comment by kwmsmith** [comment]
Update: with the docker-based improvements, we can now spin up a mongo server once and test on mac, linux, and windows via VMs.  So we can test Mongo on windows, and there's no need to remove that backend.
