### ISSUE TITLE
can you specify pd.read_csv params to odo?

### ISSUE THREAD

**Issue by dmkusner** [blaze/odo#406]
I have pandas '0.17.1' and odo '0.4.0'. I'm trying to read a csv file from the Lahman baseball database into a pandas dataframe. There are nulls in the csv, and one column contains the string 'NA', which unfortunately pandas interprets by default as a null, when it is really a string.

If I import directly into pandas using the read_csv function, I have to do something like this:

In [3]: df = pd.read_csv("Appearances.csv",na_values="",keep_default_na=False)

In [13]: df[df.columns[0:5]].head()
Out[13]:
   yearID teamID lgID   playerID  G_all
0    1871    BS1   NA  barnero01     31
1    1871    BS1   NA  barrofr01     18
2    1871    BS1   NA  birdsda01     29
3    1871    BS1   NA   conefr01     19
4    1871    BS1   NA  gouldch01     31

Is there any way to replicate this with odo? If I try:

df_odo = odo.odo("Appearances.csv",pd.DataFrame)

I get: 

Exception: Integer column has NA values in column 4

Is there any way to get odo to use the 'na_values' and 'keep_default_na' params?

**Comment by dmkusner** [comment]
Just to be clear, specifying them as extra params, like so:

df_odo = odo.odo("Appearances.csv",pd.DataFrame,na_values="",keep_default_na=False)

does not work. In fact, I've never entirely been clear on whether the extra params get applied to the source or the target.

**Comment by llllllllll** [comment]
The kwargs are being properly forwarded to `pd.read_csv`when actually coercing the csv; however, not when being discovered. You can get around this by explicitly passing the `dshape` to odo for the resulting dataframe. For example:

```python
In [1]: !cat a.csv
a,b
1,2
NA,3

In [2]: odo('a.csv', pd.DataFrame, dshape='var * {a: string, b: int64}', keep_default_na=False)
Out[2]: 
    a  b
0   1  2
1  NA  3

In [3]: _.dtypes
Out[3]: 
a    object
b     int64
dtype: object
```

If you don't know what the dshape should be, you can pass this argument to discover like:

```python
In [4]: t = resource('a.csv')

In [5]: discover(t, keep_default_na=False)
Out[5]: dshape("var * {a: ?string, b: int64}")
```

**Comment by llllllllll** [comment]
Also, all kwargs are forwarded to each edge in the graph for conversion or appending. For example, if I have 3 functions that go from `a_to_b :: A -> B`, `b_to_c :: B -> C`, and ` c_to_d :: C -> D` and I try to odo an instance of `A` into a `D` (assuming these are all registered) with the call `odo(my_a, C, a1=1, a2=2)` then that would be equivalent to the following:

```python
c_to_d(b_to_c(a_to_b(my_a, B, a1=1, a2=2), C, a1=1, a2=2), D, a1=1, a2=2)
```

It is the responsibility of each conversion function to filter out only the kwargs that are relevant to that particular conversion. For example, in the `CSV -> pd.DataFrame` edge there is code like:

```python
kwargs = keyfilter(keywords(pd.read_csv).__contains__, kwargs)
```
which filters out all of the kwargs that are not also arguments to `read_csv`.

Hopefully this helps

**Comment by dmkusner** [comment]
Appreciate the info, I'll try it tonight.

**Comment by dmkusner** [comment]
I tried the following:

In [29]: csv_file = os.path.abspath("../../data/lahman_baseball/Appearances.csv")
In [30]: csv_res = odo.resource(csvfile)
In [31]: csv_dshape = odo.discover(csv_res)
In [32]: csv_dshape
Out[32]:
dshape("""var * {
  yearID: int64,
  teamID: ?string,
  lgID: ?string,
  playerID: ?string,
  G_all: int64,
  GS: ?string,
  G_batting: int64,
  G_defense: int64,
  G_p: int64,
  G_c: int64,
  G_1b: int64,
  G_2b: int64,
  G_3b: int64,
  G_ss: int64,
  G_lf: int64,
  G_cf: int64,
  G_rf: int64,
  G_of: int64,
  G_dh: ?string,
  G_ph: ?string,
  G_pr: ?string
  }""")
In [33]: odo.odo(csvfile,pd.DataFrame,dshape=csv_dshape,na_values="",keep_default_na=False)

This resulted in the same error I got previously, namely: "Exception: Integer column has NA values in column 4"

Passing the extra parameters in addition to an explicit dshape doesn't seem to make any difference. Is there something I'm missing?

**Comment by dmkusner** [comment]
I used 'csv_file' and 'csvfile' interchangeably in the example above, but both variables are set identically so it doesn't matter.

**Comment by dmkusner** [comment]
I figured out the problem I was having -- two columns in my table had nulls, but not until over 90,000 rows in. The odo.discover() function was returning int64 for these rows, but pandas would not import the data unless these rows were defined as float64. Apparently a pandas DataFrame cannot have nulls in a column defined as int, but can in a column defined as float.

So I manually edited the datashape values for these two columns, changing them from int64 to float64. Once I did this, the dataframe loaded the data cleanly.

Thanks for the help.

**Comment by llllllllll** [comment]
> pparently a pandas DataFrame cannot have nulls in a column defined as int, but can in a column defined as float.

A word about null vs nan:
Pandas does not support null or missing data. There is no way to have an optional int or optional float column. nan is simply a valid element of floating types. Many people use this particular value as a sentinal to mean missing data

**Comment by citynorman** [comment]
I had the same problem with NANs vs integer/float columns. `dask.read_csv()` has an [assume_missing](https://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.read_csv) parameter which allows read the whole dataframe, currently I am unable to read them in blaze/odo.
