### ISSUE TITLE
ImportError: Cannot import name 'is_zero_time'

### ISSUE THREAD

**Issue by postelrich** [blaze/odo#437]
Noticed this issue.  odo worked after I updated datashape.  meta.yaml probably just needs to be updated with the appropriate version.

```
Python 3.5.1 |Anaconda 2.4.1 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.
900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from odo import odo
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f8e6b93414f5> in <module>()
----> 1 from odo import odo

C:\Users\Rich\Anaconda3\lib\site-packages\odo\__init__.py in <module>()
      9 halt_ordering()  # Turn off multipledispatch ordering
     10
---> 11 from .utils import ignoring
     12 from .convert import convert
     13 from .append import append

C:\Users\Rich\Anaconda3\lib\site-packages\odo\utils.py in <module>()
     14
     15 from datashape import dshape, Record
---> 16 from datashape.discovery import is_zero_time
     17
     18 from toolz import pluck, get, curry, keyfilter

ImportError: cannot import name 'is_zero_time'
```

**Comment by branning** [comment]
How did you install `odo` in the first place? Did you use `conda` or `pip` or directly from the git repository?

**Comment by postelrich** [comment]
`conda install odo`

then when I saw the error, I did a `conda install datashape` to pull down the latest.

`is_zero_time` was added to datashape in commit https://github.com/blaze/datashape/commit/08f9c9408a5eb18e93c971664ee93ce4a6b9fb85.  Which tag was that in?  Not sure how to see that.

**Comment by branning** [comment]
You can see the tags that include that commit near the top of the link you posted, it shows `0.5.1` and `0.5.0`.

It could be a packaging issue, though I wasn't able to reproduce it with either pip or conda. Both pulled down `datashape` version `0.5.1` and worked for me.

I do agree that the `datashape` version should be bumped to `>=0.5.0`, for both pip and odo. Based on the versions in `requirements.txt` and `meta.yml`, I don't understand why it works at all.

**Comment by postelrich** [comment]
Nah I think it just needed to be bumped.  Sorry I should have mentioned I already had odo installed and just updated it.  So I must have had the older but acceptable version of datashape.
