### ISSUE TITLE
[question] how to read a java timestamp

### ISSUE THREAD

**Issue by robsonpeixoto** [blaze/odo#480]
In Java, all timestamp use milliseconds as unit. So, I need to get the timestamp, divide by 1000 before use in python.

How can I do it using odo?

Thanks

**Comment by robsonpeixoto** [comment]
To fix the problema I put the `dshape` as a `int64`. After date be loaded in a DataFrame, I changed the column using this code:

```python
df['myDateColumn'] = pd.to_datetime(df['myDateColumn'], unit='ms')
```

What do you think about add `unit` as a parameter to `datetime`?

**Comment by llllllllll** [comment]
I think that would be useful, it is an important part of using datetimes in different systems.
