### ISSUE TITLE
appveyor

### ISSUE THREAD

**Issue by llllllllll** [blaze/odo#522]
xref: https://github.com/blaze/datashape/pull/217

In order to test against mssql (and on windows in general) we should have an appveyor build to run the test suite alongside the travis builds.

ping @thequackdaddy

I am not sure who has access to the github config for this project to actually add the hook but appveyor will let you run any project on your account. If someone does that to get an appveyor file started we can seek out someone from Continuum to enable checks in pull requests.

**Comment by necaris** [comment]
@llllllllll I might have the requisite access but if not can certainly help get additional testing set up

**Comment by necaris** [comment]
Closed via #523
