### ISSUE TITLE
Unable to parse uri to data resource

### ISSUE THREAD

**Issue by rlang2017** [blaze/odo#604]
![screenshot from 2018-02-05 16-12-07](https://user-images.githubusercontent.com/32716611/35829108-cc0bf2ca-0a8f-11e8-998f-1094fa197969.png)
![screenshot from 2018-02-05 16-11-16](https://user-images.githubusercontent.com/32716611/35829109-cc1e839a-0a8f-11e8-9bb1-d474c0738b27.png)
![screenshot from 2018-02-05 16-11-40](https://user-images.githubusercontent.com/32716611/35829110-cc3309fa-0a8f-11e8-8e3b-7512c68b0e30.png)

When trying to pass db via uri, this is the result every time.  Tried with postgres and mysql with the same result. Many different variations of argument tried according to all documentation I could find.  I have sqlalchemy and pandas installed, along with some other packages that I thought to try.  This is my first attempt to interact with db's via python, so I'm sure I'm missing something simple that is obvious to others.  Is there a comprehensive tutorial anywhere??  Please help!!

**Comment by llllllllll** [comment]
When opening an issue like this, you need to show an example of the code you attempted to run along with the output it produced. No one can help you if they don't know what is wrong.

**Comment by rlang2017** [comment]
Sorry, |||||||||||| - just added some screenshots - hope that helps.

**Comment by llllllllll** [comment]
Thanks, in general, I prefer text so I can search and copy it, but this works. Can you paste the result of `pip freeze` if you use pip, or `conda list` if you use conda? To use the db backends you would need the db driver, for example `psycopg2` for postgres or `pymysql` for mariadb. Are you sure those are installed in the env?

**Comment by rlang2017** [comment]
Here it is:  Thanks for helping out!

apturl==0.5.2
beautifulsoup4==4.4.1
blinker==1.3
Brlapi==0.6.4
chardet==2.3.0
checkbox-support==0.22
command-not-found==0.3
cryptography==1.2.3
datashape==0.5.2
decorator==4.2.1
defer==1.0.6
feedparser==5.1.3
guacamole==0.9.2
html5lib==0.999
httplib2==0.9.1
idna==2.0
Jinja2==2.8
language-selector==0.1
louis==2.6.4
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
multipledispatch==0.4.9
networkx==2.1
numpy==1.14.0
oauthlib==1.0.3
odo==0.5.0
onboard==1.2.0
padme==1.1.1
pandas==0.22.0
pexpect==4.0.1
Pillow==3.1.2
plainbox==0.25
psycopg2==2.7.3.2
ptyprocess==0.5
pyasn1==0.1.9
pycups==1.9.73
pycurl==7.43.0
pygobject==3.20.0
PyJWT==1.3.0
PyMySQL==0.8.0
pyparsing==2.0.3
python-apt==1.1.0b1
python-dateutil==2.6.1
python-debian==0.1.27
python-systemd==231
pytz==2017.3
pyxdg==0.25
reportlab==3.3.0
requests==2.9.1
sessioninstaller==0.0.0
six==1.10.0
SQLAlchemy==1.2.2
ssh-import-id==5.5
system-service==0.3
toolz==0.9.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.13.1
usb-creator==0.3.0
xdiagnose==3.8.4.1
xkit==0.0.0
XlsxWriter==0.7.3
root@user-Precision-M6700:/#

**Comment by llllllllll** [comment]
So, I think you are doing the correct thing, assuming that I am reading it all correctly. Can you evaluate:
```python
>>> from odo import resource
>>> resource.funcs
```
and post the result?

**Comment by rlang2017** [comment]
>>> from odo import resource
>>> resource.funcs
{re.compile('^http://.+$'): <function resource_url at 0x7f7944ed50d0>, re.compile('^.+\\.(txt|log)(.gz)?$'): <function resource_sas at 0x7f7944f02400>, re.compile('^.+/\\*\\..+$'): <function resource_directory at 0x7f7944ef3268>, re.compile('^s3://.*\\.json(\\.gz)?$'): <function resource_s3_json_lines at 0x7f7944ecb488>, re.compile('^.+::.+$'): <function resource_split at 0x7f7944f10598>, re.compile('^s3://.*\\.csv(\\.gz)?$'): <function resource_s3_csv at 0x7f7944ecb268>, re.compile('^hdfstore://.+$'): <function resource_hdfstore at 0x7f7944f0d1e0>, re.compile('^.*\\.json(\\.gz)?$'): <function resource_json_ambiguous at 0x7f7944ec4730>, re.compile('^ftp://.+$'): <function resource_url at 0x7f7944ed50d0>, re.compile('^s3://.*\\*.csv(\\.gz)?$'): <function resource_s3_csv_glob at 0x7f7944ecb2f0>, re.compile('^https://.+$'): <function resource_url at 0x7f7944ed50d0>, re.compile('^.*$'): <function resource_all at 0x7f7944f10488>, re.compile('^s3://.*\\.txt(\\.gz)?$'): <function resource_s3_text at 0x7f7944ecb400>, re.compile('^.+\\.(csv|tsv|ssv|data|dat)(\\.gz|\\.bz2?)?$'): <function resource_csv at 0x7f7944f219d8>, re.compile('^.+/$'): <function resource_directory_with_trailing_slash at 0x7f7944ef32f0>, re.compile('^.*\\*.+$'): <function resource_glob at 0x7f7944f21a60>, re.compile('^.*\\.jsonlines(\\.gz)?$'): <function resource_jsonlines at 0x7f7944ec47b8>, re.compile('^jsonlines://.*\\.json(\\.gz)?$'): <function resource_jsonlines at 0x7f7944ec47b8>, re.compile('^json://.*\\.json(\\.gz)?$'): <function resource_json at 0x7f7944ec46a8>}
>>>

**Comment by llllllllll** [comment]
It looks like odo isn't seeing your sql packages. What happens if you run `from odo.backends import sql`?

**Comment by rlang2017** [comment]
Sweet!  I hope that's got it.  Thanks so much!  I never expect to hear back from folks that fast.
I have to take off for the day here, but hopefully tomorrow I can start packing my csv's into the db and all will be well.  I'll post a quick thanks if all goes well.

>>> from odo.backends import sql
>>> resource('postgresql://postgres:ronotis1@127.0.0.1/bolter')
Engine(postgresql://postgres:***@127.0.0.1/bolter)
>>>

**Comment by llllllllll** [comment]
No problem! Hmm, did you import odo, then pip install the packages without restarting your Python session? If so, this should "just work" now because it attempts to import `odo.backends.sql` during the first import.

**Comment by rlang2017** [comment]
Well, now it appears I've moved on to a new problem:

>>> odo(data, 'postgresql://postgres:ronotis1@127.0.0.1/bolter::bolter')

Traceback (most recent call last):
  File "<pyshell#56>", line 1, in <module>
    odo(data, 'postgresql://postgres:ronotis1@127.0.0.1/bolter::bolter')
  File "/usr/local/lib/python3.5/dist-packages/odo/odo.py", line 91, in odo
    return into(target, source, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 143, in into_string
    return into(a, b, dshape=dshape, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/into.py", line 131, in into_object
    return append(target, source, dshape=dshape, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/backends/sql.py", line 493, in append_anything_to_sql_Table
    return append(t, convert(Iterator, o, **kwargs), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 57, in _transform
    ooc_types=ooc_types)
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 94, in path
    for src, tgt in zip(pth, pth[1:])]
  File "/usr/local/lib/python3.5/dist-packages/odo/core.py", line 94, in <listcomp>
    for src, tgt in zip(pth, pth[1:])]
AttributeError: 'DiGraph' object has no attribute 'edge'


I searched for similar issues, and found one: https://github.com/blaze/odo/issues/588, but it doesn't seem to offer a solution.  I rolled back to networkx 1.9  (as there seems to be some discussion about compatibility with 2.x) and re-imported, but I'm still getting the same error.

**Comment by necaris** [comment]
@rlang2017 When you say you re-imported, did you simply type the "import" line again, or have you quit and restarted Python? Whenever updating dependencies of any kind, I would strongly suggest doing the latter -- can you try that?

**Comment by rlang2017** [comment]
I did try that right after I made the last post, and it seems to have fixed that particular error.  I'm working on a few other problems right now and I'm hoping odo will do its thing on the next attempt.  Thanks again for all the help!

**Comment by necaris** [comment]
Closing as it appears to be resolved -- feel free to reopen if this exact error recurs.
