### ISSUE TITLE
pandas.Dataframe to mysql Table with auto_increment

### ISSUE THREAD

**Issue by JoooyZ** [blaze/odo#608]
Hi, I try to use odo to convert large df data to mysql Table, include a auto_increment id and two foreign keys, but failed.
I got the error:
`ValueError: Column names of incoming data don't match column names of existing SQL table
Names in SQL table: ['id', 'domain','count', 'client_ip_id', 'uuid_id',  'start_time']
Names from incoming data: ['client_ip_id', 'count', 'domain', 'uuid_id', 'start_time']`
 
And my code is simply like this:
`odo.odo(source=df, target="mysql://username:pswd@remote_server:port/db_name::table_name")`

How should I fix it?

**Comment by jingyu-xu** [comment]
I got the same error.
ValueError: Column names of incoming data don't match column names of existing SQL table
Names in SQL table: ['id', 'variable_code', 'zcta', 'value', 'Year']
Names from incoming data: ['variable_code', 'zcta', 'value', 'Year']

**Comment by JeromeRaghunandan** [comment]
I have the same error. How do you handle auto incrementing identity columns with odo?
